Fix the build for nginx 1.24
Fixes:

```
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /nix/store/2ysp5ichpccf4lv1wp2qcwz0bmm840f1-rtmp -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/stream \
        -o objs/addon/src/ngx_http_headers_more_headers_in.o \
        /nix/store/zx05c5lb0ivmjx6fmaa5csjrqpc7fwjc-moreheaders/src/ngx_http_headers_more_headers_in.c
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /nix/store/2ysp5ichpccf4lv1wp2qcwz0bmm840f1-rtmp -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/stream \
        -o objs/addon/src/ngx_http_headers_more_util.o \
        /nix/store/zx05c5lb0ivmjx6fmaa5csjrqpc7fwjc-moreheaders/src/ngx_http_headers_more_util.c
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /nix/store/2ysp5ichpccf4lv1wp2qcwz0bmm840f1-rtmp -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/stream \
        -o objs/addon/9wmvjckqn5nkc51jk4krzvwvywn875xy-fancyindex/ngx_http_fancyindex_module.o \
        /nix/store/9wmvjckqn5nkc51jk4krzvwvywn875xy-fancyindex/ngx_http_fancyindex_module.c
In file included from src/event/ngx_event.h:526,
                 from src/http/ngx_http_upstream.h:14,
                 from src/http/ngx_http.h:34,
                 from /nix/store/9wmvjckqn5nkc51jk4krzvwvywn875xy-fancyindex/ngx_http_fancyindex_module.c:27:
src/event/ngx_event_udp.h:38:27: error: field 'pkt6' has incomplete type
   38 |     struct in6_pktinfo    pkt6;
      |                           ^~~~
make[1]: *** [objs/Makefile:2091: objs/addon/9wmvjckqn5nkc51jk4krzvwvywn875xy-fancyindex/ngx_http_fancyindex_module.o] Error 1
make[1]: Leaving directory '/build/nginx-1.24.0'
make: *** [Makefile:10: build] Error 2
error: builder for '/nix/store/fa8cd5pp2a5fl5hrsk69mmkplhd3b74z-nginx-1.24.0.drv' failed with exit code 2
```